# this docker compose file is for development only
services:
  frontend:
    container_name: godoxy-frontend-next
    restart: no
    network_mode: host
    image: godoxy-frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes: # for hot reloading
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./node_modules:/app/node_modules:ro
      - ./next.config.js:/app/next.config.js:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
    labels:
      proxy.aliases: godoxy-dev
      proxy.*: |
        port: 3002
        healthcheck:
          disabled: true
        homepage:
          show: false
