# this docker compose file is for development only
services:
  frontend:
    container_name: godoxy-frontend
    restart: no
    network_mode: host
    image: godoxy-frontend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes: # for hot reloading
      - ./app:/app/app:ro
      - ./components:/app/components:ro
      - ./config:/app/config:ro
      - ./public:/app/public:ro
      - ./styles:/app/styles:ro
      - ./types:/app/types:ro
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    labels:
      proxy.aliases: godoxy,godoxy-test
      proxy.*: |
        port: 3001
        healthcheck:
          disabled: true
        homepage:
          show: false
